item: PUFFERFISH_BUCKET
item2: PUFFERFISH
name: "&6Магическое &3Ведро"
name2: "&6Зловещая &3Рыбка"
description:
  - "&#D61D86Скрывает игроков в хабе"
description2:
  - "&#D61D86Показывает игроков в хабе"
slot: 0
cooldown: 3 # В секундах