name: HubPlayer
version: '1.0.17-OmxRealm'
main: org.dw363.HubPlayer
api-version: '1.21'
load: STARTUP
authors: [dw363]
description: Плагин добавляющий предмет для скрытия игроков в хабе. Сделано специально для сервера OmxRealm. Project The OMX.
website: https://github.com/Hacker123ter
commands:
  hubplayer:
    description: Основная команда HubPlayer
    usage: /<command> hide|reload|show
    permission: hubplayer.command
    permission-message: У вас нет прав для использования данной команды.
permissions:
  hubplayer.command:
    description: Позволяет перезагрузить конфигурацию плагина.
    default: op